/*
* generated by Xtext
*/
package org.limadelic.raconteur.ui.contentassist;

import org.limadelic.raconteur.ui.contentassist.AbstractFeatureProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class FeatureProposalProvider extends AbstractFeatureProposalProvider {

}
