/*
 * generated by Xtext
 */
package org.limadelic.raconteur;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class FeatureRuntimeModule extends org.limadelic.raconteur.AbstractFeatureRuntimeModule {

}
