/*
 * generated by Xtext
 */
package org.limadelic.raconteur.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class FeatureUiModule extends org.limadelic.raconteur.ui.AbstractFeatureUiModule {
	public FeatureUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
